require          'thor'


class Sys < Thor

# package_name "susu"


desc 'test', 'Run the unit tests for the Sys library'
def test

	require_relative 'test/run'

	TidBits::Sys::TestSuite.run

end


end
