require          'thor'

require          'awesome_print'
require          'byebug'
require          'pry'

require_relative '../../lib/tidbits'
require_relative 'test/run'


class Options < Thor


desc 'test', 'Run the unit tests for the Options library'

def test

	Susu::Options::TestSuite.run

end


end # class Options
